#!/bin/sh
set -e

##
# variables
localbase=${LOCALBASE:-$(realpath "$(dirname "$0")"/..)}
libexec="${localbase}"/libexec
txt="${CERTBOT_VALIDATION}"

##
# main
xml=$("${libexec}"/get-hosts)
argv=$(echo "${xml}" | "${libexec}"/emit-argv)
"${libexec}"/set-hosts -d "HostName1=_acme-challenge" \
                       -d "RecordType1=TXT" \
                       -d "Address1=${txt}" \
                       -d "ttl1=60" \
                       ${argv}
echo
echo "[-] Wait 15 minutes"
echo
sleep 900
