#!/bin/sh
set -e

##
# variables
i=2
IFS=

##
# main
while read -r line; do
    if echo "${line}" | grep -q "<host"; then
        hostname=$(echo "$line" | sed -n 's/.* Name="\([^"]*\)".*/\1/p')
        recordtype=$(echo "$line" | sed -n 's/.*Type="\([^"]*\)".*/\1/p')
        address=$(echo "$line" | sed -n 's/.*Address="\([^"]*\)".*/\1/p')
        ttl=$(echo "$line" | sed -n 's/.*TTL="\([^"]*\)".*/\1/p')
        if [ "${hostname}" = "_acme-challenge" ]; then
            continue
        fi
        echo "-d \"HostName${i}=${hostname}\" " \
             "-d \"RecordType${i}=${recordtype}\" " \
             "-d \"Address${i}=${address}\" " \
             "-d \"TTL${i}=${ttl}\""
        i=$(expr ${i} + 1)
    fi
done
