#!/bin/sh -e

##
# variables
. "${HOME}"/.env
host="${NAMECHEAP_APIHOST:-api.namecheap.com}"
user="${NAMECHEAP_APIUSER}"
key="${NAMECHEAP_APIKEY}"
myip="${NAMECHEAP_CLIENTIP}"
sld="${NAMECHEAP_SLD}"
tld="${NAMECHEAP_TLD}"

##
# main
i=2
records=$(
    curl -s "https://${host}/xml.response?" \
     -d "ApiUser=${user}" \
     -d "ApiKey=${key}" \
     -d "UserName=${user}" \
     -d "ClientIp=${myip}" \
     -d "Command=namecheap.domains.dns.getHosts" \
     -d "SLD=${sld}" \
     -d "TLD=${tld}"
)
echo "${records}" |
  grep -oP '(?<=<host>).+?(?=</host>)' |
  while read -r line; do
      hostname=$(echo "$line" | grep -oP '(?<=<Name>)[^<]+')
      recordtype=$(echo "$line" | grep -oP '(?<=<Type>)[^<]+')
      address=$(echo "$line" | grep -oP '(?<=<Address>)[^<]+')
      ttl=$(echo "$line" | grep -oP '(?<=<TTL>)[^<]+')
      if [ "${hostname}" = "_acme-challenge" ]; then
          echo ""
      else
          echo "-d \"HostName${i}=${hostname}\" " \
              "-d \"RecordType${i}=${recordtype}\" " \
              "-d \"Address${i}=${address}\" " \
              "-d \"TTL${i}=${ttl}\""
      fi
      i=$(expr ${i} + 1)
  done
