#!/bin/sh
set -e

##
# variables
. "${HOME}"/.env
host="${NAMECHEAP_APIHOST:-api.namecheap.com}"
user="${NAMECHEAP_APIUSER}"
key="${NAMECHEAP_APIKEY}"
myip="${NAMECHEAP_CLIENTIP}"
sld="${NAMECHEAP_SLD}"
tld="${NAMECHEAP_TLD}"

##
# main
curl -s "https://${host}/xml.response?" \
     -d "ApiUser=${user}" \
     -d "ApiKey=${key}" \
     -d "UserName=${user}" \
     -d "ClientIp=${myip}" \
     -d "SLD=${sld}" \
     -d "TLD=${tld}" \
     -d "Command=namecheap.domains.dns.getHosts"
