#!/bin/sh
set -e

##
# variables
localbase=$(realpath "$(dirname "$0")"/../..)
libexec="${localbase}"/libexec/certbot+cron
challenge="${CERTBOT_VALIDATION}"

##
# functions
printok()
{
    printf "ok: %s\n" "${1}" > /dev/stdout
}

##
# main
xml=$("${libexec}"/get-hosts)
argv=$(echo "${xml}" | "${libexec}"/emit-argv)
"${libexec}"/set-hosts -d "HostName1=_acme-challenge" \
                       -d "RecordType1=TXT" \
                       -d "Address1=${challenge}" \
                       -d "ttl1=60" \
                       ${argv}
printok "challenge set"
sleep 900
