#!/bin/sh
set -e

##
# variables
user="_certbot"
localbase=$(realpath "$(dirname "$0")"/../..)
libexec="${localbase}"/libexec/certbot+cron

##
# functions
printok()
{
    printf "ok: %s" "${1}" > /dev/stdout
}

printerr()
{
    printf "error: %s" "${1}" > /dev/stderr
}

verify_allowfile()
{
    allowfile="/var/cron/allow"
    if [ -e "${allowfile}" ]; then
        if grep -Eqe "^${user}$" "${allowfile}"; then
            printok "${user} found in ${allowfile}"
        else
            printerr "${user} was not found in ${allowfile}"
            exit 1
        fi
    fi
}

verify_denyfile()
{
    denyfile="/var/cron/deny"
    if [ -e "${denyfile}" ]; then
        if grep -Eqe "^${user}$" "${denyfile}"; then
            printerr "${user} was found in ${denyfile}"
            exit 1
        else
            printok "${user} not found in ${denyfile}"
        fi
    fi
}

install_crontab()
{
    tab="${localbase}"/share/certbot+cron/crontab
    dest="/var/cron/tabs/${user}"
    if [ -e "${dest}" ]; then
        yes | crontab -u "${user}" -r
        printok "crontab removed"
    fi
    crontab -u "${user}" "${tab}"
    chmod u=rw,go= "${dest}"
    printok "crontab added"
}

##
# main
if [ "$(id -u)" != "0" ]; then
    printerr "you must be root"
    exit 1
else
    verify_denyfile
    verify_allowfile
    install_crontab
fi
