#!/bin/sh
set -e

##
# variables
user="_certbot"
localbase=$(realpath "$(dirname "$0")"/../..)
libexec="${localbase}"/libexec/certbot+cron
homedir="${localbase}"/share/certbot+cron/home/_certbot

##
# functions
printok()
{
    printf "ok: %s\n" "${1}" > /dev/stdout
}

printerr()
{
    printf "error: %s\n" "${1}" > /dev/stderr
}

##
# main
if [ "$(id -u)" != "0" ]; then
    printerr "you must be root"
    exit 1
elif id "-u" "${user}" > /dev/null 2>&1; then
    find "${homedir}"
         -maxdepth 1 \
         -exec cp -Rfv {} /home/"${user}" \;
    printok "user ${user} already exists"
else
    set -x
    pw useradd \
        -n "${user}" \
        -M "u=rwx,g=rx,o=" \
        -s "/sbin/nologin" \
        -c "certbot+cron user" \
        -d "/home/${user}" \
        -mk "${homedir}"
    set +x
    printok "${user} user created"
fi
set -x
find /home/"${user}" \
    -type d \
    -exec chmod u=rwx,g=rx,o= {} \;
find /home/"${user}" \
    -type f \
    -exec chmod u=rwx,g=rx,o= {} \;
chmod u=rw,g=r,o= /home/"${user}"/.env
set +x
printok "home directory ready"
