#!/bin/sh
set -e

##
# variables
user="_certbot"
localbase=$(realpath "$(dirname "$0")"/../..)
libexec="${localbase}"/libexec/certbot+cron

##
# functions
printok()
{
    printf "ok: %s" "${1}" > /dev/stdout
}

printerr()
{
    printf "error: %s" "${1}" > /dev/stderr
}

install_crontab()
{
    tab="${localbase}"/share/certbot+cron/crontab
    dest="/var/cron/tabs/${user}"
    if [ -e "${dest}" ]; then
        yes | crontab -u "${user}" -r
        printok "crontab removed"
    fi
    crontab -u "${user}" "${tab}"
    chmod u=rw,go= "${dest}"
    printok "crontab added"
}

##
# main
allowfile="/var/cron/allow"
if [ -e "${allowfile}" ]; then
    if ! grep -q "${user}" "${allowfile}"; then
        printerr "${user} was not found in ${allowfile}"
        exit 1
    fi
    printok "${user} found in ${allowfile}"
fi
install_crontab
